name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Getting prerequisites
      run: |
        sudo apt -y install g++
        sudo apt -y install libcurl4-openssl-dev
        sudo apt-get -y install libncurses5-dev libncursesw5-dev
        sudo apt -y install cmake
    - name: Building application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
  
  Debian:
    runs-on: ubuntu-latest
    container: debian
    steps:
      - uses: actions/checkout@v2
      - name: Getting prerequisites
        run: |
          apt update && apt -y install g++ libcurl4-openssl-dev libncurses5-dev libncursesw5-dev git cmake
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git && cd Todo && mkdir build && cd build && cmake .. && cmake --build .


  Arch-Linux:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v2
      - name: Getting prerequisites
        run: |
          pacman -Syy --noconfirm
          pacman -Syu --noconfirm
          pacman -Sy gcc --noconfirm
          pacman -S curl --noconfirm
          pacman -S ncurses --noconfirm
          pacman -S git --noconfirm
          pacman -S cmake --noconfirm
          pacman -S make --noconfirm
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .

  CentOS:
    runs-on: ubuntu-latest
    container: centos
    steps:
      - uses: actions/checkout@v2
      - name: Getting prerequisites
        run: |
          yum -y update
          yum -y group install "Development Tools"
          yum -y install libcurl --allowerasing
          yum -y install curl-devel
          yum -y install ncurses-devel
          yum -y install cmake
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .

  Fedora-Linux:
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - uses: actions/checkout@v2
      - name: Getting prerequisites
        run: |
          dnf -y upgrade
          dnf -y install git
          dnf -y install gcc-c++
          dnf -y install libcurl-devel
          dnf -y install ncurses-devel
          dnf -y install cmake
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .

  OpenSUSE-Leap:
    runs-on: ubuntu-latest
    container: opensuse/leap
    steps:
      - name: Getting prerequisites
        run: |
          zypper refresh
          zypper update -y
          zypper install -y gcc-c++
          zypper install -y libcurl-devel
          zypper install -y ncurses-devel
          zypper install -y cmake
          zypper install -y git
      - uses: actions/checkout@v2
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .

  OpenSUSE-Tumbleweed:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed
    steps:
      - name: Getting prerequisites
        run: |
          zypper refresh
          zypper update -y
          zypper install -y gcc-c++
          zypper install -y libcurl-devel
          zypper install -y ncurses-devel
          zypper install -y cmake
          zypper install -y git
      - uses: actions/checkout@v2
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .
  
  Kali-Linux:
    runs-on: ubuntu-latest
    container: kalilinux/kali-rolling
    steps:
      - uses: actions/checkout@v2
      - name: Getting prerequisites
        run: |
          apt -y update
          apt -y upgrade
          apt -y install g++
          apt -y install libcurl4-openssl-dev
          apt-get -y install libncurses5-dev libncursesw5-dev
          apt -y install cmake
          apt -y install git
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .

  Alpine:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - uses: actions/checkout@v2
      - name: Getting prerequisites
        run: |
          apk update
          apk upgrade
          apk add g++ ncurses-dev curl-dev git cmake make
      - name: Building application
        run: | 
          git clone https://github.com/GhostVaibhav/Todo.git
          cd Todo
          mkdir build
          cd build
          cmake ..
          cmake --build .
        
  Windows:
  
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Getting prerequisites for building on MinGW
      run: |
        start prereq.bat 1
        exit
    - name: Getting prerequisites for building on Visual Studio
      run: |
        start prereq.bat 2
        exit
    - name: Compiling the build file
      run: |
        g++ build.cpp -o build
    - name: Compiling and linking the main file
      run: |
        start build.exe main
        exit
  
  MacOS:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Installing prerequisites
      run: |
        brew install gcc
        brew install make
        brew install curl
        brew install ncurses
        brew install cmake
        brew tap nlohmann/json
        brew install nlohmann-json
    - name: Building and compiling the build file using CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
